### ISSUE TITLE
Replace axios with @digitalbazaar/http-client

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/bedrock-manifest-proxy#4]

**Comment by mattcollier** [comment]
The initial PR is still open, so it's a good time to go ahead and get this done.  https://github.com/digitalbazaar/bedrock-manifest-proxy/pull/2

**Comment by dlongley** [comment]
Closed by 4ce21fc8e509a7edebdd502f7f6614ca51d849e7.
